#!/bin/bash
## docker-enter
## @author gdm85
## @author jpetazzo
##
## this is an heavily modified version from jpetazzo's original
## it uses /proc/*/environ to retrieve a correct container environment
## and then performs other sorcerery tricks to setup an usable shell
## both for interactive ad non-interactive use within containers
##
#

if [ -z "$1" ]; then
	echo "Usage: docker-enter CONTAINER [COMMAND [ARG]...]"
	echo ""
	echo "Enters the Docker CONTAINER and executes the specified COMMAND."
	echo "If COMMAND is not specified, runs an interactive shell in CONTAINER."
	exit 1
fi

BASENAME=$(dirname $(readlink -m $0)) || exit $?

. "$BASENAME/nsenter.lib.sh" || exit $?

CID="$1"
shift

if [ $# -eq 0 ]; then
	echo "--> docker-enter: now entering container $CID with an interactive shell" 1>&2
	docker_nsenter "$CID" su -m -l -- root
else
	docker_nsenter "$CID" "$@"
fi
